# Generated by Django 4.2.1 on 2023-05-30 11:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("418cc5a4-e043-4e22-8aa2-e2a4c016bf2e"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("std_number", models.CharField(max_length=10)),
            ],
        ),
    ]
